<?php

$lang['adminrole_module']= array(
    'basic'=> '基础功能',
    'privilege'=> '权限模块',
    'mall'=> '商城模块',
    'member'=> '会员模块',
    'membervip'=> '新会员模块',
    'hotel'=> '酒店订房',
    'report'=> '报表功能',
    'publics'=> '微信公众号',
    'distribute'=> '分销管理',
    'soma'=> '社交商城（新）',
    'pay'=> '支付配置',
    'okpay'=> '快乐付',
    'club'=> '社群客',
    'company'=> '协议客',
    'notify'=> '订单通知',
    'price'=> '比价系统',
    'iapi-hotel'=> '新版酒店订房',
);
$lang['adminrole_controller']= array(
    'auth'=> '认证管理',
    'node'=> '菜单管理',
    'adminuser'=> '后台管理员',
    'adminrole'=> '管理员权限',
    'adminlog'=> '管理员日志',
    //privilege module end

    'codegen'=> '代码生成',
    'notice'=> '公告消息',
    'upload'=> '上传接口',
	//basic module end

    'address'=> '邮寄地址',
    'advs'=> '轮播图',
    'category'=> '商品分类',
    'comments'=> '商品评论',
    'goods'=> '商品管理',
    'invoice'=> '发票申请',
    'orders'=> '订单管理',
    'topics'=> '专题管理',
    'carts'=> '购物车',
    //mall module end

    'cms_block'=> '内容管理',
    'reward_rule'=> '分销绩效规则',
    'reward_benefit'=> '分销绩效明细',
    'message_wxtemp_template'=> '订单邮寄',
    'message_wxtemp_record'=> '订单邮寄',
    'consumer_shipping'=> '订单邮寄',
    'activity_package'=> '套票活动',
    'category_package'=> '套票分类',
    'adv'=> '首页设置',
    'asset_customer'=> '资产账户',
    'consumer_order'=> '消费记录',
    'gift_order'=> '赠送记录',
    'product_package'=> '套票管理',
    'refund_order'=> '退款记录',
    'sales_order'=> '订单管理',
    'sales_invoice'=> '发票管理',
    'sales_voucher_exchange'=> '兑换记录',
    'sales_voucher_template'=> '批量生成模板',
    'shard_db'=> '分片配置',
    'statis_sales'=> '销售统计',
    'theme_config'=> '皮肤配置',
    'theme_config_use'=> '选择皮肤',
    'sales_rule'=> '促销规则',
    'sales_coupon'=> '优惠券规则',
    'share_config'=> '分享配置',
    'activity_killsec'=> '秒杀活动',
    'sales_reserve_product'=> '大客户首页',
    'sales_reserve'=> '大客户预定',
    'gift_theme'=> '赠送主题',
    'sales_voucher_exchange'=> '兑换券记录',
    'sales_voucher_template'=> '兑换券模版',
    'statis_product'=> '商品数据',
    'center_activity'=> '中心平台同步列表',
    'center_activity_adv'=> '中心平台焦点图',
    'center_share_config'=> '中心平台分享配置',
    
    //soma module end
    
	'basicinfo' => '基础信息',
	'bonusdetail'=>'积分详情',
	'bonusexplain'=>'积分说明',
	'bonusrule'=>'积分规则',
	'cardlist'=>'卡券列表',
	'cardorder'=>'卡券订单',
	'cardtype'=>'卡券种类',
	'carduserule'=>'卡券使用规则',
	'chargelist'=>'充值列表',
	'chargeorder'=>'充值订单',
	'membercat'=>'行业编辑',
	'memberlevel'=>'会员等级',
    'memberlist'=>'会员列表',
	'memgetcardlist'=>'会员领取卡券',
	'promoterule'=>'营销规则',
	'registerinfo'=>'注册配置',
    'resetinfo' =>'重置密码',
    'memberlogin'=>'登录配置',
    'vcardmanage'=>'会员卡管理',
    //member module end
    'loginconfig' => '会员登录配置',
    'membercard' =>'会员优惠券',
    'membercenter' =>'会员中心',
    'membercredit' =>'会员积分',
    'memberdeposit' =>'会员储值',
    'membermanage' =>'会员管理',
    'membermodel' =>'会员登录',
    'membermodify'=>'会员完善资料',
    'memberservicerule'=>'会员卡券规则',
    'regconfig' => '会员注册配置',
    'resetpasswordconfig' => '会员重置密码配置',
    'updatepasswordconfig' => '会员修改密码配置',
    'staffs'=> '分销人员',
    'distribute'=> '分销业绩',
	'distri_report'=>'分销报表',
	'send_records'=>'发放记录',
	'msgs'=>'信息管理',
	'departments'=>'部门管理',
    'publics'=> '公众号管理',
    'menu'=> '自定义菜单',
    'keywords'=> '关键词回复',
    'news'=> '图文管理',


    'club'=>'社群客销售员',
    'club_customer'=>'社群客成员',
    'club_list'=>'社群客列表',
    
);
$lang['adminrole_action'] = array(
    'index' => 'index方法',
    'grid' => '查看列表',
    'add' => '新增数据',
    'edit' => '查看详情',
    'edit_post' => '更新数据',
    'delete' => '删除数据',
    'unbinding'=>'解绑会员',
    'card_user_info'=>'优惠券详细',
    'edit_credit'=>'积分调整',
    'edit_balance'=>'储值调整',
    //base action end

    'do_upload'=> '文件上传',
    'browse'=> '文件浏览',
	//basic module end
    
    'icons' => '图标字体',
    'nofound' => '404页面',
    'deny' => '拒绝访问！',
    'dashboard' => '个人面板',
    'updb' => '更新数据（慎用）',
    'profile' => '个人资料',
    'profile_post' => '个人资料',
    'show_consume_code'=> '显示核销二维码',
    'consume_handle' => '手动核销商品',
    'admin_qrcode'=> '显示管理员授权二维码',
    'authid_handle'=> '管理员授权处理',
    'ajax_admin_hotels'=> '管理员所选酒店',
    'staff'=> '账号列表',
    'plus'=> '新增账号',
    'plus_post'=> '保存账号',
    'remove'=> '账号账号',
    //privilege module end
    
    'edit_focus' => '修改轮播图',
    'export' => '数据导出',
    'export_list' => '数据导出',
    'qrcode_front' => '显示二维码',
    'ajax_cardsave' => '产品绑定卡券ID',
    'ajax_cardlist' => '拉取卡券类型清单',
    'review' => '审核记录',
    'comfirm' => '确认订单',
    //mall module end
    

    'consumer_post' => '核销处理',
    'booking_post' => '预约处理',
    'booking' => '预约查看',
    'consumer' => '核销处理',
    'get_cancel_label' => '取消标签',
    'get_check_label' => '检查标签',
    'get_pending_label' => '申请标签',
    'get_refund_label' => '退款标签',
    'cancel' => '取消',
    'pending' => '申请',
    'refund' => '退款',
    'check' => '检查',
    'edit_get' => '链接提交',
    'kind_do_upload' => '多图片上传',

    'export_order'=> '导出订单记录',
    'show_order'=> '显示订单信息',
    'batch'=> '批量邮寄',
    'batch_post'=> '批量邮寄提交',
    'remark'=> '添加备注',
    'modify_mail_info'=> '修改发货信息',
    'hold_post'=> '挂起',
    'refresh'=> '同步优惠券',
    'expire_edit'=> '查看有效期',
    'expire_post'=> '修改有效期',
    'batch_edit'=> '批量邮寄',

    'sync'=> '同步到中心平台',


    //soma module end
    
	'get_configs'=>'读取报表字段配置',
	'save_configs'=>'保存报表字段配置',
	'saler_grades'=>'分销员绩效(时段)',
	'exp_saler_grades'=>'分销员绩效(时段)导出',


    'club_edit'=>'编辑社群客',
    'club_batch_auth'=>'审核社群客',
    'save_club'=>'保存社群客',

    'admin_index'=>'运营版首页',
    'hotel_index'=>'酒店版首页',
    'detail'=>'比价详情',
    'admin_match'=>'匹配概览',
    'hotels_match'=>'匹配详情',
    'hotel_edit'=>'匹配修改',
    // price module end

);
//用于操作名称冲突分辨，优先级低于 $lang['adminrole_action'] ，需要上面为空才生效
$lang['adminrole_conflict'] = array(
    'export'=> array(
        'address'=> '导出记录', 
        'adminuser'=> '导出管理员列表', 
    ),
);